name: rate Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        
    - name: Run a script that needs the GitHub Token
      run: |
        pipenv run python web-app/github_api.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
